### ISSUE TITLE
Error: 550 5.7.1 relaying not allowed to

### ISSUE THREAD

**Issue by blackxMan** [0x4139/node-pmta#1]
Hi guys, thnk for this great work but i have this issus 

PMTA: 250 2.0.0 ok

PMTA: 550 5.7.1 relaying not allowed to <fayssal.tahtoub@gmail.com> in "RCPT TO: <fayssal.tahtoub@gmail.com>"

/home/fynx/test-script/pmtajs/lib/Connection.js:32
		throw new Error(message);

**Comment by 0x4139** [comment]
gmail does not allow relaying because that will mean it will move alot of spam, "mail from" cannot be from an isp if you are sending from port 25 you need to authenticate before that,  its not a library issue it's how mailing works

**Comment by 0x4139** [comment]
do you need any more help?
